### ISSUE TITLE
Демо проект WapPlusDemo -> не отображается реклама

### ISSUE THREAD

**Issue by EvgenyKarkan** [WapStart/plus1-ios-sdk#8]
Создал сегодня на веб портале приложение, ему был присвоен ID, приложение уже прошло модерацию.
Теперь пытаюсь c полученным ID запустить демо проект - но рекламы там не вижу. 

Может быть нужны какие дополнительные действия с моей стороны?

**Comment by klestoff** [comment]
Евгений, спасибо за обращение. Это не является проблемой SDK. По настройкам вас проконсультирует наша тех.поддержка.
